# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

require "vagrant-host-shell"
require "vagrant-junos"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "ndo_public", primary: true do |ndo|
    ndo.vm.box = "juniper/netdevops-ubuntu1404"
    ndo.vm.box_version = ">= 0.2.6"
    ndo.vm.hostname = "NetDevOps-Public"
    ndo.vm.network "public_network",
                   netmask: "255.255.252.0",
                   ip: "10.10.0.10"
    ndo.vm.synced_folder "../", "/vagrant", disabled: false
    ndo.ssh.password = "vagrant"

    ndo.vm.provider "virtualbox" do |v|
    end

    ndo.vm.provision "shell" do |s|
      s.path = "scripts/ndopub-setup.sh"
    end
  end

  config.vm.define "ndo_private", primary: true do |ndo|
    ndo.vm.box = "juniper/netdevops-ubuntu1404-headless"
    ndo.vm.box_version = ">= 0.2.6"
    ndo.vm.hostname = "NetDevOps-Private"
    ndo.vm.network "private_network",
                   ip: "192.168.10.10",
                   virtualbox__intnet: "NetDevOps-Private"
    ndo.vm.synced_folder "../", "/vagrant", disabled: false

    ndo.vm.provider "virtualbox" do |v|
    end

    ndo.vm.provision "shell" do |s|
      s.path = "scripts/ndopri-setup.sh"
    end
  end

  config.vm.define "vsrx_headend" do |srx|
    srx.vm.box = "juniper/ffp-12.1X47-D20.7"
    srx.vm.box_version = ">= 0.5.0"
    srx.vm.hostname = "vSRX-Headend"
    srx.vm.provider "virtualbox" do |v|
      v.check_guest_additions = false
    end
    srx.vm.network "public_network",
                   ip: "10.10.0.5",
                   netmask: "255.255.252.0",
                   nic_type: 'virtio'
    srx.vm.network "private_network",
                   ip: "192.168.10.1",
                   virtualbox__intnet: "NetDevOps-Private",
                   nic_type: 'virtio'
    srx.vm.synced_folder "", "/vagrant", disabled: true

    srx.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", "3072"]
    end

    srx.vm.provision "file", source: "scripts/srx-setup.sh", destination: "/tmp/srx-setup.sh"
    srx.vm.provision "file", source: "scripts/srx-vpnstints.sh", destination: "/tmp/srx-vpnstints.sh"
    srx.vm.provision :host_shell do |host_shell|
      host_shell.inline = 'vagrant ssh vsrx_headend -c "/usr/sbin/cli -f /tmp/srx-setup.sh"'
    end
    srx.vm.provision :host_shell do |host_shell|
        host_shell.inline = 'vagrant ssh vsrx_headend -c "/usr/sbin/cli -f /tmp/srx-vpnstints.sh"'
    end
  end
end
