---
- name: Add vpn ike gateway
  hosts: vpn_headend
  connection: local
  gather_facts: no
  vars:
    junos_user: "root"
    junos_password: "Juniper"
    build_dir: "/tmp/"
    pods: [ { "addr_lo0": "10.255.255.1/32","addr_st0": "10.255.1.2/30","addr_wan": "10.10.0.29","id": 1,"pod_number": 1}]

  tasks:
    - name: Build gateway templates
      template: src=templates/add_vpn_gateway.set.j2 dest={{build_dir}}/add_vpn_gateway.set

    - name: Apply address book entries
      junos_install_config: host={{ inventory_hostname }} user={{ junos_user }} passwd={{ junos_password }} file={{ build_dir }}/add_vpn_gateway.set overwrite=no logfile=logs/{{ inventory_hostname }}.log
